### PR TITLE
Add UI Draft

### PR DESCRIPTION
**Pull request by SZB3748**
## Pages
- Create Account
- Login
- Main
- Settings

### Create Account
- Shows on startup if no local account info is found
- Contains inputs "Account Name" and "Password"
- Has a link to the [Login](#login) page for if the user already has an account
- Has a button to create the account

### Login
- Shows on startup if local account info is found
- Contains input "Account Name" and "Password"
- Has a button to login

### Main
- The main page where chat messages are sent from and viewed
- Contains a left bar
    - Search bar for filtering the Chat Destination list (top)
    - Chat Destination list (middle)
    - Buttons for adding a Chat Destination and going to [Settings](#settings) (bottom)
- Has top bar for info, middle for viewing messages, and bottom bar for sending messages

### Settings
- Has a left bar which is a list of links to all of the different settings categories
- The only category that is currently added is Appearances

## Notes
- This is just a draft and is mainly for figuring out where stuff will be positioned on the screen.
- If you wish to check all of the pages, you can add the following line of code under the `MainWindow window` definition in [main.cpp](https://github.com/Goodyear-Smith-Dev/DecentralChat/blob/ui-draft/src/qt/decentralchat-qt/main.cpp) to switch which page to view by the number of arguments passed to the app (build/debug/DecentralChat.exe):
```
window.findChild<QStackedWidget*>("stackedWidget")->setCurrentIndex(argc-1);
```

### CODE REVIEW

**Comment by Ryan-M-Smith** [comment]
`argc` is the argument count...`std::atoi(argv[0]) - 1` will get the number passed on the command line, convert it to an int, and then subtract one.

**Comment by Ryan-M-Smith** [comment]
Oh man VSCode was not happy about your stylesheet substitution thing. So many red lines in the qss file. They just don't know what they're missing out on.

**Review by Ryan-M-Smith — APPROVED** [review]
Everything looks good! I made some small, random adjustments to stuff here and there, but functionality-wise everything is fine.

**Comment by SZB3748** [comment]
> `argc` is the argument count...`std::atoi(argv[0]) - 1` will get the number passed on the command line, convert it to an int, and then subtract one.

Well it was easier to just use argc then pass a number of args to determine the number.
Like `build/debug/DecentralChat.exe a b` would go to the main page (index 2).

**Comment by Ryan-M-Smith** [comment]
Oh okay. I didn't know it was supposed to work that way. I guess that works too.

**Pull request merged**
